
package proxy1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProductWs", targetNamespace = "http://service.soapserver.aya.net/", wsdlLocation = "http://localhost:8085/ProductWs?wsdl")
public class ProductWs
    extends Service
{

    private static final URL PRODUCTWS_WSDL_LOCATION;
    private static final WebServiceException PRODUCTWS_EXCEPTION;
    private static final QName PRODUCTWS_QNAME = new QName("http://service.soapserver.aya.net/", "ProductWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/ProductWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTWS_WSDL_LOCATION = url;
        PRODUCTWS_EXCEPTION = e;
    }

    public ProductWs() {
        super(__getWsdlLocation(), PRODUCTWS_QNAME);
    }

    public ProductWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTWS_QNAME, features);
    }

    public ProductWs(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTWS_QNAME);
    }

    public ProductWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTWS_QNAME, features);
    }

    public ProductWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductwebService
     */
    @WebEndpoint(name = "ProductwebServicePort")
    public ProductwebService getProductwebServicePort() {
        return super.getPort(new QName("http://service.soapserver.aya.net/", "ProductwebServicePort"), ProductwebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductwebService
     */
    @WebEndpoint(name = "ProductwebServicePort")
    public ProductwebService getProductwebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soapserver.aya.net/", "ProductwebServicePort"), ProductwebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTWS_EXCEPTION!= null) {
            throw PRODUCTWS_EXCEPTION;
        }
        return PRODUCTWS_WSDL_LOCATION;
    }

}
