
package proxy1;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductwebService", targetNamespace = "http://service.soapserver.aya.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductwebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy1.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.AddProductResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/addProductRequest", output = "http://service.soapserver.aya.net/ProductwebService/addProductResponse")
    public Product addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy1.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.GetProductByIdResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/getProductByIdRequest", output = "http://service.soapserver.aya.net/ProductwebService/getProductByIdResponse")
    public Product getProductById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param price
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellingprice", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.Sellingprice")
    @ResponseWrapper(localName = "sellingpriceResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.SellingpriceResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/sellingpriceRequest", output = "http://service.soapserver.aya.net/ProductwebService/sellingpriceResponse")
    public Double sellingprice(
        @WebParam(name = "price", targetNamespace = "")
        Double price);

    /**
     * 
     * @return
     *     returns java.util.List<proxy1.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.GetAllProductsResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/getAllProductsRequest", output = "http://service.soapserver.aya.net/ProductwebService/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.DeleteProductResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/deleteProductRequest", output = "http://service.soapserver.aya.net/ProductwebService/deleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns proxy1.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://service.soapserver.aya.net/", className = "proxy1.UpdateProductResponse")
    @Action(input = "http://service.soapserver.aya.net/ProductwebService/updateProductRequest", output = "http://service.soapserver.aya.net/ProductwebService/updateProductResponse")
    public Product updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Product arg1);

}
